### PR TITLE
fix handling of invalid key-share

### PR DESCRIPTION
**Pull request by NoName115**
When tlslite-ng detected invalid key-share, undefined variable was used.
This PR should fix that and implement correct handling of key-share.

fix for testing https://github.com/tomato42/tlsfuzzer/issues/364

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/310)

### CODE REVIEW

**Comment by tomato42** [comment]
This pull request **introduces 1 alert** when merging 822767541ea8e3539c560013113367ae55b5cef6 into 1b6ec55dcd5160b0056704fe4d65fb54eb7cf432 - [view on LGTM.com](https://lgtm.com/projects/g/tomato42/tlslite-ng/rev/pr-04e3d6d9404d1ee6bf9613bbc906e6824808ef89)

**new alerts:**

* 1 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by NoName115** [comment]
Fixed.

Test `Test 53 - resumption in TLSv1.3` in tlslite-ng fails as an empty key_share extension is sent.

**Comment by tomato42** [comment]
> tlslite-ng fails as an empty key_share extension is sent.

empty list in extension or empty extension? 

because the former is allowed and is intended:
https://github.com/tomato42/tlslite-ng/blob/1b6ec55dcd5160b0056704fe4d65fb54eb7cf432/tests/tlstest.py#L836-L839

**Comment by tomato42** [comment]
looks good, thanks!

**Pull request merged**
