### PR TITLE
Cookie extension parser

### PR DESCRIPTION
**Pull request by tomato42**
Add parser for the cookie extension, share code with the renegotiation_info extension

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/263)

### CODE REVIEW

**Comment by tomato42** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging 61880909bff2685a0443e6b5d2919076a3c3eaae into 2ca8c0c15313c73985866007fc7fdfa102fa6d62 - [view on lgtm.com](https://lgtm.com/projects/g/tomato42/tlslite-ng/rev/pr-6b2be0fc2b970e9eb96c094eab0180b80cad6dfb)

**new alerts:**

* 1 for \_\_eq\_\_ not overridden when adding attributes

**fixed alerts:**

* 1 for \_\_eq\_\_ not overridden when adding attributes

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by tomato42** [comment]
better test coverage for VarBytesExtension missing

**Comment by tomato42** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging 05cfb553ea694782e1197c3b2866dcab5ca4356f into a683a9d81b66d3fa79e586c0bcb37d4a86aa447a - [view on lgtm.com](https://lgtm.com/projects/g/tomato42/tlslite-ng/rev/pr-36dae02811d99e8819d3aac5c6b7aad738e5fcf7)

**new alerts:**

* 1 for \_\_eq\_\_ not overridden when adding attributes

**fixed alerts:**

* 1 for \_\_eq\_\_ not overridden when adding attributes

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by tomato42** [comment]
lgtm alerts are false positives - the parent `__eq__` uses the `extData()` which is overridden

**Comment by ep69** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[tlslite/extensions.py, line 344 at r4](https://reviewable.io/reviews/tomato42/tlslite-ng/263#-LDq49SPCuuykUXjxbIq:-LDq49SPCuuykUXjxbIr:b-aw5ynp) ([raw file](https://github.com/tomato42/tlslite-ng/blob/7c1999f0e299a5cbe30cedc6615eb53d422208e4/tlslite/extensions.py#L344)):*
> ```Python
>     def __setattr__(self, name, value):
>         """Set the special field value."""
>         if name == '_field_name':
> ```

Is this some special case that if we want to set _field_name and we have _field_name == "_field_name", we want to do that in the superclass? Otherwise this conditional statement would be pointless, right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/263)*

**Comment by ep69** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/263)*

**Comment by tomato42** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tlslite/extensions.py, line 344 at r4](https://reviewable.io/reviews/tomato42/tlslite-ng/263#-LDq49SPCuuykUXjxbIq:-LDqXDW2211zaygAw3tH:b-m470ej) ([raw file](https://github.com/tomato42/tlslite-ng/blob/7c1999f0e299a5cbe30cedc6615eb53d422208e4/tlslite/extensions.py#L344)):*
<details><summary><i>Previously, ep69 (Stanislav Židek) wrote…</i></summary><blockquote>

Is this some special case that if we want to set _field_name and we have _field_name == "_field_name", we want to do that in the superclass? Otherwise this conditional statement would be pointless, right?
</blockquote></details>

yes, it's a special case

superclass in this case is the python `object` implementation, so it's the generic __setattr__ and __getattr__

we're overriding them because we want to fake existence of an attribute specified in constructor, but that name needs to be saved in some value, so it *itself* is accessed through setattr and getattr, so for those calls we need to call the native implementation

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/263)*

**Comment by tomato42** [comment]
ok, this unnecessary code should be removed now:
https://github.com/tomato42/tlslite-ng/blob/7c1999f0e299a5cbe30cedc6615eb53d422208e4/tlslite/extensions.py#L344-L346

**Comment by tomato42** [comment]
This pull request **fixes 1 alert** when merging 40464fdb18e1526afe923e36788729377b6f66ef into 5f6110b7ca6a19fdd79bc64f230526df30ee6c0f - [view on lgtm.com](https://lgtm.com/projects/g/tomato42/tlslite-ng/rev/pr-bd07cc324c7104a738534119d435517163412b59)

**fixed alerts:**

* 1 for \_\_eq\_\_ not overridden when adding attributes

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by ep69** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tlslite/extensions.py, line 292 at r10](https://reviewable.io/reviews/tomato42/tlslite-ng/263#-LDw23DW5D4raVPLrO_s:-LDw23DW5D4raVPLrO_t:b-vo4pj0) ([raw file](https://github.com/tomato42/tlslite-ng/blob/40464fdb18e1526afe923e36788729377b6f66ef/tlslite/extensions.py#L292)):*
> ```Python
> 
>     Used for handling arbitrary extensions that deal with a single value
>     in paylod (either an opaque data, single value or single array.
> ```

typos - s/paylod/payload/ + unfinished parenthesis

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/263)*

**Comment by tomato42** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tlslite/extensions.py, line 292 at r10](https://reviewable.io/reviews/tomato42/tlslite-ng/263#-LDw23DW5D4raVPLrO_s:-LDw7nnH9PVeaTk0cfXm:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/40464fdb18e1526afe923e36788729377b6f66ef/tlslite/extensions.py#L292)):*
<details><summary><i>Previously, ep69 (Stanislav Židek) wrote…</i></summary><blockquote>

typos - s/paylod/payload/ + unfinished parenthesis
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/263)*

**Comment by ep69** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/263)*

**Pull request merged**
