### PR TITLE
Post handshake auth

### LINKED ISSUE #208: Post handshake client authentication in TLS 1.3
Support for authentication post handshake

depends on #207

### PR DESCRIPTION
**Pull request by tomato42**
add support for Post Handshake Authentication (the post_handshake_auth extension)

depends on #196 and #341 
fixes #208 

TODO
 - [x] change from callback to a list of client certificates in HandshakeSettings
 - [x] test coverage

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/350)

### CODE REVIEW

**Comment by tomato42** [comment]
This pull request **introduces 9 alerts** when merging 1992ced2b33b9dee661d1f0d43d397f595765919 into 849f1d15cd49ec7fc62a4c5564f32fd857791ba7 - [view on LGTM.com](https://lgtm.com/projects/g/tomato42/tlslite-ng/rev/pr-a8119af6eb9cead5edf18c8645ac614c171f8ac7)

**new alerts:**

* 3 for Unused local variable
* 3 for Unused import
* 1 for \_\_eq\_\_ not overridden when adding attributes
* 1 for First argument of a method is not named &#39;self&#39;
* 1 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by tomato42** [comment]
This pull request **introduces 9 alerts** when merging 68ecf2438dc959e60620673d5a576305caeed0df into 849f1d15cd49ec7fc62a4c5564f32fd857791ba7 - [view on LGTM.com](https://lgtm.com/projects/g/tomato42/tlslite-ng/rev/pr-3ef0e5c6c68d933df50cdffda018257fdfaf7d02)

**new alerts:**

* 3 for Unused local variable
* 3 for Unused import
* 1 for \_\_eq\_\_ not overridden when adding attributes
* 1 for First argument of a method is not named &#39;self&#39;
* 1 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ueno** [comment]
It looks good to me. I was just wondering if `certificate_required` alert shall be implemented in this PR?

**Comment by tomato42** [comment]
> It looks good to me. I was just wondering if `certificate_required` alert shall be implemented in this PR?

good point, that actually would be the most portable way of handling required certificate... I'll add it as an option

**Pull request merged**
