### PR TITLE
Python3 protocol fixes

### PR DESCRIPTION
**Pull request by tomato42**
Few things weren't fixed for python 3, address them

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/126)

### CODE REVIEW

**Comment by tomato42** [comment]
@The-Mule r?

the code climate failure is unfixable, pylint is quite picky about the formatting of its waiver lines

**Comment by The-Mule** [comment]
r+

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/tomato42/tlslite-ng/126#-:-KQNBByDmBzt5HwzVb3D:b32wu6)*

**Comment by The-Mule** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/tomato42/tlslite-ng/126)*

**Comment by tomato42** [comment]
thanks!

**Pull request merged**
