### PR TITLE
Add brainpool support

### LINKED ISSUE #428: Support for Brainpool curves
Hi,

first of all: thank you for this awesome project! I'm using it for TLS penetration testing and it is much easier to use than full fledges crypto libraries (e.g. OpenSSL or BouncyCastle).

During the testing I am now faced with the necessity to validate a certificate using the BrainpoolP256r1 curve. As far as I know this isn't supported yet. At least these curves aren't listed within CURVE_NAMES of handshakesettings.py. Nevertheless the used [ecdsa library](https://github.com/warner/python-ecdsa) seem to support these curves.

Are there any plans regarding the inclusion of brainpool curves in the future? Which steps or changes would be necessary to add support?

Thanks!

Version used: 0.8.0-alpha38

### PR DESCRIPTION
**Pull request by pytz**
fixes #428

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/430)

### CODE REVIEW

**Review by tomato42 — CHANGES_REQUESTED** [review]
please rebase on top of master. It needs to be based off of master for CI to pass, and I won't merge without CI passing.

> Reviewed 2 of 2 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-:-MKLIhcTEVA0lrbYPVjv:b-n5xrv8)* status: all files reviewed, 9 unresolved discussions (waiting on @pytz)

___
*[tests/serverBrainpoolP256r1ECKey.pem, line 3 at r2](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLKtjd23N9gV_EUBhY:-MKLKtjd23N9gV_EUBhZ:b-a3rxf2) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf273fea147493836b05050824a4c0840fb7a9f4/tests/serverBrainpoolP256r1ECKey.pem#L3)):*
> ```
> -----BEGIN EC PARAMETERS-----
> BgkrJAMDAggBAQc=
> -----END EC PARAMETERS-----
> ```

EC PARAMETERS are not necessary and we don't include them in the other key files
___
*[tests/serverBrainpoolP384r1ECKey.pem, line 3 at r2](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLLM9L9JNKEF9ytnoP:-MKLLM9L9JNKEF9ytnoQ:b-2guby3) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf273fea147493836b05050824a4c0840fb7a9f4/tests/serverBrainpoolP384r1ECKey.pem#L3)):*
> ```
> -----BEGIN EC PARAMETERS-----
> BgkrJAMDAggBAQs=
> -----END EC PARAMETERS-----
> ```

same here
___
*[tests/serverBrainpoolP512r1ECKey.pem, line 3 at r2](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLLOOM49vbXsnagInl:-MKLLOON53sv46FlbVf2:bji28bi) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf273fea147493836b05050824a4c0840fb7a9f4/tests/serverBrainpoolP512r1ECKey.pem#L3)):*
> ```
> -----BEGIN EC PARAMETERS-----
> BgkrJAMDAggBAQ0=
> -----END EC PARAMETERS-----
> ```

and here
___
*[tests/tlstest.py, line 316 at r2](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLMKBZ9_GfjDTFYReD:-MKLMKBZ9_GfjDTFYReE:b9zdvvj) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf273fea147493836b05050824a4c0840fb7a9f4/tests/tlstest.py#L316)):*
> ```Python
>         settings.maxVersion = (3, 3)
>         settings.eccCurves = [curve]
>         settings.keyShares = [curve]
> ```

for tls 1.2 there's no reason to set key shares
___
*[tests/tlstest.py, line 1890 at r2](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLLsNkEY3uL6k6Zdib:-MKLLsNl4bxbaWGOYeGu:b5bpkuh) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf273fea147493836b05050824a4c0840fb7a9f4/tests/tlstest.py#L1890)):*
> ```Python
>         settings.maxVersion = (3, 3)
>         settings.eccCurves = [curve, "secp256r1"]
>         settings.keyShares = [curve, "secp256r1"]
> ```

key shares have no meaning for TLS 1.2
___
*[tlslite/handshakesettings.py, line 40 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLJOCaC_qnUf1nxF-u:-MKLJOCaC_qnUf1nxF-v:b62ou0h) ([raw file](https://github.com/tomato42/tlslite-ng/blob/2316e6e05072e5afa337324e9fbf62e19fbbec1e/tlslite/handshakesettings.py#L40)):*
> ```Python
> ALL_CURVE_NAMES = CURVE_NAMES + ["secp256k1", "brainpoolP512r1", "brainpoolP320r1",
>                                  "brainpoolP384r1", "brainpoolP320r1", "brainpoolP256r1",
>                                  "brainpoolP224r1", "brainpoolP192r1"]
> ```

there are two problems: distributions like fedora hobble python-ecdsa package and removes some curves, like the `secp224r1` below, I'm not sure about brainpool, but it's likely they'll want to remove it too, so we may need a flag similar to ecdsaAllCurves

second thing: we currently depend on ecdsa>=0.13.3 while brainpool curves were added in 0.14
___
*[tlslite/handshakesettings.py, line 53 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLMgws3alFm0wIMEQP:-MKLMgws3alFm0wIMEQQ:bjx3q2x) ([raw file](https://github.com/tomato42/tlslite-ng/blob/2316e6e05072e5afa337324e9fbf62e19fbbec1e/tlslite/handshakesettings.py#L53)):*
> ```Python
>                  "brainpoolP160r1": ('BRAINPOOLP160r1',),
>                  "brainpoolP192r1": ('BRAINPOOLP192r1',),
>                  "brainpoolP224r1": ('BRAINPOOLP224r1',),
> ```

why did you remove the other sizes?
___
*[tlslite/handshakesettings.py, line 57 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLItiaE3g5w6One07Q:-MKLItiaE3g5w6One07R:b-9pjpmy) ([raw file](https://github.com/tomato42/tlslite-ng/blob/2316e6e05072e5afa337324e9fbf62e19fbbec1e/tlslite/handshakesettings.py#L57)):*
> ```Python
>                  "brainpoolP320r1": ('BRAINPOOLP320r1',),
>                  "brainpoolP384r1": ('BRAINPOOLP384r1',),
>                  "brainpoolP512r1": ('BRAINPOOLP512r1',)}
> ```

is this necessary? I thought that the code that use s CURVE_ALIASES ignores case...
___
*[tlslite/utils/ecc.py, line 41 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLKACL7zbEwrD8fqiT:-MKLKACL7zbEwrD8fqiU:but774m) ([raw file](https://github.com/tomato42/tlslite-ng/blob/2316e6e05072e5afa337324e9fbf62e19fbbec1e/tlslite/utils/ecc.py#L41)):*
> ```Python
>                 'secp521r1':ecdsa.NIST521p,
>                 'secp256k1':ecdsa.SECP256k1,
>                 'brainpoolP160r1': ecdsa.BRAINPOOLP160r1,
> ```

same as for secp224r1 and ecdsaAllCurves

**Review by pytz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/430)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @1, @2, and @tomato42)

___
*[tests/serverBrainpoolP256r1ECKey.pem, line 3 at r2](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLKtjd23N9gV_EUBhY:-MKROuFI4p1DqCWfwOi8:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf273fea147493836b05050824a4c0840fb7a9f4/tests/serverBrainpoolP256r1ECKey.pem#L3)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

EC PARAMETERS are not necessary and we don't include them in the other key files
</blockquote></details>

Done.
___
*[tests/serverBrainpoolP384r1ECKey.pem, line 3 at r2](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLLM9L9JNKEF9ytnoP:-MKROyAR4ea_svaUjree:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf273fea147493836b05050824a4c0840fb7a9f4/tests/serverBrainpoolP384r1ECKey.pem#L3)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[tests/serverBrainpoolP512r1ECKey.pem, line 3 at r2](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLLOOM49vbXsnagInl:-MKRP6nb5FJuNh8iq9m-:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf273fea147493836b05050824a4c0840fb7a9f4/tests/serverBrainpoolP512r1ECKey.pem#L3)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

and here
</blockquote></details>

Done.
___
*[tests/tlstest.py, line 316 at r2](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLMKBZ9_GfjDTFYReD:-MKRP8p33V9VkDlKzQyW:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf273fea147493836b05050824a4c0840fb7a9f4/tests/tlstest.py#L316)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

for tls 1.2 there's no reason to set key shares
</blockquote></details>

Done.
___
*[tests/tlstest.py, line 1890 at r2](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLLsNkEY3uL6k6Zdib:-MKRP9dY23fZ55UzgSlv:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf273fea147493836b05050824a4c0840fb7a9f4/tests/tlstest.py#L1890)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

key shares have no meaning for TLS 1.2
</blockquote></details>

Done.
___
*[tlslite/handshakesettings.py, line 40 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLJOCaC_qnUf1nxF-u:-MKRPAli2IA7CfWeTUIh:b-fxd9i5) ([raw file](https://github.com/tomato42/tlslite-ng/blob/2316e6e05072e5afa337324e9fbf62e19fbbec1e/tlslite/handshakesettings.py#L40)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

there are two problems: distributions like fedora hobble python-ecdsa package and removes some curves, like the `secp224r1` below, I'm not sure about brainpool, but it's likely they'll want to remove it too, so we may need a flag similar to ecdsaAllCurves

second thing: we currently depend on ecdsa>=0.13.3 while brainpool curves were added in 0.14
</blockquote></details>

@1: I couldn't find any futher information on this topic. Currently I added BrainpoolP256r1, ...P384r1 and ...P512r1. So there shouldn't be a problem with low bit curves (?). Or do you think adding them to the ecdsaAllCurves would be enougth?

@2: so updating the requirements.txt would be necessary. Would such an update be ok (at least it is a larger change)?
___
*[tlslite/handshakesettings.py, line 53 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLMgws3alFm0wIMEQP:-MKRREL92_M467APPZXO:b-19hlri) ([raw file](https://github.com/tomato42/tlslite-ng/blob/2316e6e05072e5afa337324e9fbf62e19fbbec1e/tlslite/handshakesettings.py#L53)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why did you remove the other sizes?
</blockquote></details>

They are not listed within constants.py. Based on the comment the brainpool curves came from RFC7027 only 256, 384 and 512 are supported. They are also not listed in https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8
___
*[tlslite/handshakesettings.py, line 57 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLItiaE3g5w6One07Q:-MKRU43cBuXAF3D_DlXw:b-f2tzz6) ([raw file](https://github.com/tomato42/tlslite-ng/blob/2316e6e05072e5afa337324e9fbf62e19fbbec1e/tlslite/handshakesettings.py#L57)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

is this necessary? I thought that the code that use s CURVE_ALIASES ignores case...
</blockquote></details>

Based on my test, yes. When I comment out the mapping lines it raises an error when connecting with openssl s_client:

tlslite.errors.TLSLocalAlert: handshake_failure: The curve in the public key is not supported by the client: None
___
*[tlslite/utils/ecc.py, line 41 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLKACL7zbEwrD8fqiT:-MKRW32N4_PgJt-Aygd0:b2ss7xm) ([raw file](https://github.com/tomato42/tlslite-ng/blob/2316e6e05072e5afa337324e9fbf62e19fbbec1e/tlslite/utils/ecc.py#L41)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same as for secp224r1 and ecdsaAllCurves
</blockquote></details>

see comment above

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r3, 5 of 9 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/430)* status: all files reviewed, 4 unresolved discussions (waiting on @1, @2, and @pytz)

*[a discussion](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKRs4ze21fGVfe7axwr:-MKRs4ze21fGVfe7axws:b2vyhh) (no related file):*
I don't see the code to check against use of brainpool curves with TLS 1.3 in HandshakeSettings...

---
___
*[tests/tlstest.py, line 316 at r5](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKRrq0M2-V34q2j8fhW:-MKRrq0M2-V34q2j8fhX:b2aqi0l) ([raw file](https://github.com/tomato42/tlslite-ng/blob/f7d86ae14cdc150bf2e20cbaaf9caf0109883ae9/tests/tlstest.py#L316)):*
> ```Python
>         settings.maxVersion = (3, 3)
>         settings.eccCurves = [curve]
>         settings.keyShares = []
> ```

by set, I meant in general, it shouldn't be necessary to change it from the default at all
if it's necessary to clear this setting, then it's a bug that need to get fixed—it's hardly a convenient API otherwise
___
*[tests/tlstest.py, line 1890 at r5](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKRt0jB1D7HDEBeJ3lJ:-MKRt0jB1D7HDEBeJ3lK:b-2guby3) ([raw file](https://github.com/tomato42/tlslite-ng/blob/f7d86ae14cdc150bf2e20cbaaf9caf0109883ae9/tests/tlstest.py#L1890)):*
> ```Python
>         settings.maxVersion = (3, 3)
>         settings.eccCurves = [curve, "secp256r1"]
>         settings.keyShares = []
> ```

same here
___
*[tlslite/handshakesettings.py, line 40 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLJOCaC_qnUf1nxF-u:-MKRtgTu5We_x-mskY8l:btqtt4e) ([raw file](https://github.com/tomato42/tlslite-ng/blob/2316e6e05072e5afa337324e9fbf62e19fbbec1e/tlslite/handshakesettings.py#L40)):*
<details><summary><i>Previously, pytz wrote…</i></summary><blockquote>

@1: I couldn't find any futher information on this topic. Currently I added BrainpoolP256r1, ...P384r1 and ...P512r1. So there shouldn't be a problem with low bit curves (?). Or do you think adding them to the ecdsaAllCurves would be enougth?

@2: so updating the requirements.txt would be necessary. Would such an update be ok (at least it is a larger change)?
</blockquote></details>

low bit curves aren't used in TLS, so yeah, we don't need them in ALL_CURVE_NAMES

I don't insist on compatibility with old version, I'm ok with just bumping the required version

but I'll need to check what's the situation in Fedora with the package, if it includes 'em or not
___
*[tlslite/handshakesettings.py, line 53 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLMgws3alFm0wIMEQP:-MKRrEY51XRgfGq8q1WS:b-z0x16s) ([raw file](https://github.com/tomato42/tlslite-ng/blob/2316e6e05072e5afa337324e9fbf62e19fbbec1e/tlslite/handshakesettings.py#L53)):*
<details><summary><i>Previously, pytz wrote…</i></summary><blockquote>

They are not listed within constants.py. Based on the comment the brainpool curves came from RFC7027 only 256, 384 and 512 are supported. They are also not listed in https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8
</blockquote></details>

ah, right
___
*[tlslite/handshakesettings.py, line 57 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLItiaE3g5w6One07Q:-MKRrQpv4aOpIDNJJrD2:b32wtd) ([raw file](https://github.com/tomato42/tlslite-ng/blob/2316e6e05072e5afa337324e9fbf62e19fbbec1e/tlslite/handshakesettings.py#L57)):*
<details><summary><i>Previously, pytz wrote…</i></summary><blockquote>

Based on my test, yes. When I comment out the mapping lines it raises an error when connecting with openssl s_client:

tlslite.errors.TLSLocalAlert: handshake_failure: The curve in the public key is not supported by the client: None
</blockquote></details>

ok

**Review by pytz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/430)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @1, @2, and @tomato42)

*[a discussion](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKRs4ze21fGVfe7axwr:-MKWNjU4CXaDbOXhyk0U:bb76j73) (no related file):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I don't see the code to check against use of brainpool curves with TLS 1.3 in HandshakeSettings...
</blockquote></details>

Right it was still missing. I added this check now. This should only apply to the key shares setting and not to the enabled curves via eccCurves, right?

---
___
*[tests/tlstest.py, line 316 at r5](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKRrq0M2-V34q2j8fhW:-MKWO0Gf9lxI5nVQORdN:b-230e94) ([raw file](https://github.com/tomato42/tlslite-ng/blob/f7d86ae14cdc150bf2e20cbaaf9caf0109883ae9/tests/tlstest.py#L316)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

by set, I meant in general, it shouldn't be necessary to change it from the default at all
if it's necessary to clear this setting, then it's a bug that need to get fixed—it's hardly a convenient API otherwise
</blockquote></details>

I'm afraid it is a bug than. This test case follows the same settings as the test "Two good ECDSA certs - secp256r1, TLSv1.2". There keyShares is also cleared. Removing that line in the already existing test case leads to an error:

ValueError: Key shares for not enabled groups specified: ['x25519']

This check should not even be necessary as the test case is TLS 1.2 only. Key shares shouldn't be checked because maxVersion != (3, 4). Should I rather create another issue or fix this check by including a check for "if other.maxVersion == (3, 4)"?
___
*[tests/tlstest.py, line 1890 at r5](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKRt0jB1D7HDEBeJ3lJ:-MKWPW644MQYvIdjCu2x:b2ss7xm) ([raw file](https://github.com/tomato42/tlslite-ng/blob/f7d86ae14cdc150bf2e20cbaaf9caf0109883ae9/tests/tlstest.py#L1890)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same here
</blockquote></details>

see comment above
___
*[tlslite/handshakesettings.py, line 40 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLJOCaC_qnUf1nxF-u:-MKRY7YJA5IjuUGNBvOL:b-c7nxeo) ([raw file](https://github.com/tomato42/tlslite-ng/blob/2316e6e05072e5afa337324e9fbf62e19fbbec1e/tlslite/handshakesettings.py#L40)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

low bit curves aren't used in TLS, so yeah, we don't need them in ALL_CURVE_NAMES

I don't insist on compatibility with old version, I'm ok with just bumping the required version

but I'll need to check what's the situation in Fedora with the package, if it includes 'em or not
</blockquote></details>

I bumped up the version in requirements.txt

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/430)* status: all files reviewed, 4 unresolved discussions (waiting on @pytz and @tomato42)

*[a discussion](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKRs4ze21fGVfe7axwr:-MKadIDiBcrL43xxdJZ8:b-f8puij) (no related file):*
<details><summary><i>Previously, pytz wrote…</i></summary><blockquote>

Right it was still missing. I added this check now. This should only apply to the key shares setting and not to the enabled curves via eccCurves, right?
</blockquote></details>

no, it should apply to `eccCurves`,  key shares setting is unused in TLS 1.2 and for TLS 1.3 I'm pretty sure we have code do verify that the keyShares are subset of eccCurves...

---
___
*[tlslite/handshakesettings.py, line 40 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKLJOCaC_qnUf1nxF-u:-MKaf87B7n5fHgViqNRm:b-ulwwi6) ([raw file](https://github.com/tomato42/tlslite-ng/blob/2316e6e05072e5afa337324e9fbf62e19fbbec1e/tlslite/handshakesettings.py#L40)):*
<details><summary><i>Previously, pytz wrote…</i></summary><blockquote>

I bumped up the version in requirements.txt
</blockquote></details>

I've checked the newest Fedoras (33 and rawhide, aka 34) and it does include brainpool curves
so looks like requirements.txt is the only change needed
___
*[tlslite/handshakesettings.py, line 465 at r6](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKae16cCED0e-TRXUaH:-MKae16eAcCukL2WHk80:b-l7rgzt) ([raw file](https://github.com/tomato42/tlslite-ng/blob/a665537daa53411d56aebbc7c9d68ee4606dea5d/tlslite/handshakesettings.py#L465)):*
> ```Python
>         # TLS 1.3 limits the allowed groups in client key share advertisement (RFC 8446,ch. 4.2.7.)
>         if other.maxVersion == (3, 4):
>             forbiddenGroup = HandshakeSettings._not_matching(other.keyShares, TLS13_PERMITTED_GROUPS)
> ```

this should be for `eccCurves` not `keyShares`

**Review by pytz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/430)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @pytz and @tomato42)

___
*[tlslite/handshakesettings.py, line 465 at r6](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKae16cCED0e-TRXUaH:-MKfB_Vx3OvDHbJXKYgi:b4yf9pg) ([raw file](https://github.com/tomato42/tlslite-ng/blob/a665537daa53411d56aebbc7c9d68ee4606dea5d/tlslite/handshakesettings.py#L465)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

this should be for `eccCurves` not `keyShares`
</blockquote></details>

Changed it to eccCurves. Together with the keyShares <= eccCurves check this should be ok.

**Review by tomato42 — APPROVED** [review]
ok, looks good, now we just need to wait for Travis (the queue is super long for the past two days: https://www.traviscistatus.com/)

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-:-MKfDIcg81CfbCTy1gLc:b-cgabjo)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[tests/tlstest.py, line 316 at r5](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKRrq0M2-V34q2j8fhW:-MKfCtlDBFyIsnz3upQr:brzmdqc) ([raw file](https://github.com/tomato42/tlslite-ng/blob/f7d86ae14cdc150bf2e20cbaaf9caf0109883ae9/tests/tlstest.py#L316)):*
<details><summary><i>Previously, pytz wrote…</i></summary><blockquote>

I'm afraid it is a bug than. This test case follows the same settings as the test "Two good ECDSA certs - secp256r1, TLSv1.2". There keyShares is also cleared. Removing that line in the already existing test case leads to an error:

ValueError: Key shares for not enabled groups specified: ['x25519']

This check should not even be necessary as the test case is TLS 1.2 only. Key shares shouldn't be checked because maxVersion != (3, 4). Should I rather create another issue or fix this check by including a check for "if other.maxVersion == (3, 4)"?
</blockquote></details>

ok, please create another issue then
___
*[tests/tlstest.py, line 1890 at r5](https://reviewable.io/reviews/tomato42/tlslite-ng/430#-MKRt0jB1D7HDEBeJ3lJ:-MKfD2De-1khBvOmNzLP:b32wtd) ([raw file](https://github.com/tomato42/tlslite-ng/blob/f7d86ae14cdc150bf2e20cbaaf9caf0109883ae9/tests/tlstest.py#L1890)):*
<details><summary><i>Previously, pytz wrote…</i></summary><blockquote>

see comment above
</blockquote></details>

ok

**Comment by tomato42** [comment]
thank you!

**Pull request merged**
