### PR TITLE
AES fixes

### PR DESCRIPTION
**Pull request by t184256**
Basically most of the #377, but for AES.

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/386)

### CODE REVIEW

**Comment by tomato42** [comment]
will need to be rebased on top of #387

**Comment by tomato42** [comment]
@t184256 ok #387 merged, the builds should be passing now

**Comment by t184256** [comment]
Several pylint directive applications later, Travis is finally green now.

**Comment by tomato42** [comment]
looks good, thanks!

**Pull request merged**
