### PR TITLE
add dependency on unittest for development

### PR DESCRIPTION
**Pull request by tomato42**

### CODE REVIEW

**Comment by tomato42** [comment]
@FiachAntaw: could you take a look? Should fix the issue with CONTRIBUTING.md you mentioned in #80

**Comment by FiachAntaw** [comment]
I think the 'mock' module is distributed as a separate module for python 2 and isn't included in unittest2. It's needed by [unit_tests/test_tlslite_recordlayer.py](https://github.com/tomato42/tlslite-ng/blob/54f47aa166c7d4c4134a67817301f3dcff202d7e/unit_tests/test_tlslite_tlsrecordlayer.py).

I'm testing the dependency list by doing the following to generate a fresh virtualenv:
```shell
cd tlslite-ng
# Make python2 virtualenv (needs virtualenv/virtualenvwrapper)
mkvirtualenv tlslite-test -p `which python2`
# Add local python3 binaries/libraries to the virtualenv
mkvirtualenv tlslite-test -p `which python3`
# Install dependencies
pip install unittest2 ecdsa pylint diff_cover coverage hypothesis tackpy m2crypto pycrypto gmpy
pip3 install ecdsa pylint diff_cover coverage hypothesis tackpy m2crypto pycrypto gmpy
# Run tests
make test-dev
```

Which at present fails with an ImportError on mock in the aforementioned file. Running `pip install mock` fixes the problem and all tests then complete without errors.

**Comment by tomato42** [comment]
@FiachAntaw how about now? I've added explicit dependency on `mock`

**Comment by FiachAntaw** [comment]
Looks good to me.

**Pull request merged**
