### PR TITLE
support for extended master secret, RFC 7627

### LINKED ISSUE #24: Add support for extended master secret
Implement https://tools.ietf.org/html/draft-ietf-tls-session-hash-06

### PR DESCRIPTION
**Pull request by tomato42**
fixes #24

### CODE REVIEW

**Comment by tomato42** [comment]
should also have config to force the use of it and reject if the other side doesn't support it

**Comment by tomato42** [comment]
@The-Mule: r?

**Comment by The-Mule** [comment]
Looks good, r+.

**Comment by tomato42** [comment]
@The-Mule: Thanks!

**Pull request merged**
